#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local usr_lib_dir="$PACKAGE_USER_LIB_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # files
  local tmp_file="$name.tar.gz"
  local lib_dir="./apache-${name}-${PACKAGE_CORE_VERSION#v}"
  local bin_file="./apache-${name}-${PACKAGE_CORE_VERSION#v}/bin/mvn"

  # prepare context
  cd $tmp_dir

  # reference: https://maven.apache.org/download.cgi
  # example: (@TODO apache official will remove some)
  #   https://dlcdn.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  #   https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz (@#TODO removed)
  #   https://dlcdn.apache.org/maven/maven-3/3.8.7/binaries/apache-maven-3.8.7-bin.tar.gz
  #
  # or: https://www.digitalocean.com/community/tutorials/install-maven-linux-ubuntu
  #   https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  # 
  # or: https://mirrors.aliyun.com/apache/maven/maven-3
  #   https://mirrors.aliyun.com/apache/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
  #   https://mirrors.aliyun.com/apache/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/maven-3/${PACKAGE_CORE_VERSION#v}/binaries/apache-${name}-${PACKAGE_CORE_VERSION#v}-bin.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading from ${url} ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # make executable
  log::info "[$(timestamp)][package][$name] making executable ..."
  chmod 755 $bin_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  if [ -d "$usr_lib_dir/${name}" ]; then
    log::info "[$(timestamp)][package][$name] removing old lib ..."
    sudo rm -rf $usr_lib_dir/${name}
  fi
  sudo mv $lib_dir $usr_lib_dir/${name}

  # bin
  log::info "[$(timestamp)][package][$name] bin mvn/maven ..."
  sudo ln -sf $usr_lib_dir/${name}/bin/mvn $usr_bin_dir/${PACKAGE_CORE_BIN_NAME}
  sudo ln -sf $usr_lib_dir/${name}/bin/mvn $usr_bin_dir/${name}

  # profile
  log::success "[$(timestamp)][package][$name] config MAVEN_HOME=$usr_lib_dir/$name to global env file ..."
  local envs=$(
    cat <<-END
export MAVEN_HOME=$usr_lib_dir/$name
END
  )
  config::profile "# ZMICRO PACKAGE MAVEN #" "$envs"

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
