#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # files
  local tmp_file="$name.tar.gz"
  local usr_lib_dir="/usr/local/lib/maven"
  local bin_file="./apache-${name}-${PACKAGE_CORE_VERSION#v}/bin/mvn"

  # prepare context
  cd $tmp_dir

  # reference: https://maven.apache.org/download.cgi
  # example:
  #   https://dlcdn.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  #   https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
  # 
  # or: https://www.digitalocean.com/community/tutorials/install-maven-linux-ubuntu
  #   https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/maven-3/${PACKAGE_CORE_VERSION#v}/binaries/apache-${name}-${PACKAGE_CORE_VERSION#v}-bin.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # make executable
  log::info "[$(timestamp)][package][$name] making executable ..."
  chmod 755 $bin_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  sudo mv ./apache-${name}-${PACKAGE_CORE_VERSION#v} $usr_lib_dir

  # bin
  log::info "[$(timestamp)][package][$name] bin mvn/maven ..."
  sudo ln -sf $usr_lib_dir/bin/mvn $usr_bin_dir/mvn
  sudo ln -sf $usr_lib_dir/bin/mvn $usr_bin_dir/maven

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
